### PR TITLE
Allow all hit types

### PR DESCRIPTION
**Pull request by vfportero**
We're using this library to send ecommerce transactions server side and we had make this changes to allow "transaction" hittype.

It would be great if you apply this PR to update the NuGet repo.

Thank you.

### CODE REVIEW

**Comment by kburnik** [comment]
Hi, thanks for the patch. I'm not actively maintaining this repo nor the NuGet package. I've forked this to support .net 4.5. If there's a way to transfer the nuget package to you, please let me know.

**Comment by kburnik** [comment]
If you have a NuGet account, just send me your username and I can set you as an owner so you can push the update. I could also add you as a collaborator on the github repo.

WDYT? :)

**Comment by vfportero** [comment]
Hi @kburnik!

Perfect, I can push the update to the Nuget package for you if you want :)

My Nuget username is vfportero.

Thanks!

**Review by kburnik — APPROVED** [review]
LGTM.

**Comment by kburnik** [comment]
Added you as a collaborator, I believe you should be able to merge it yourself. Also, you should receive an invite for NuGet.

**Pull request merged**
